Docs/dashboard dynamic statistics
Monofony/SymfonyStarter pull request #260
Opened 2020-01-26 16:21 UTC by lucasballyn

With this PR I provide documentation for creating custom statistics. With was introduced with #232

2020-01-26 16:22 UTC, lucasballyn commented
Hi @loic425, 

I was not sure if I also had to push the built documentation or not. If so, please let me now. I'll push it.

2020-01-28 09:38 UTC, loic425 commented on docs/cookbook/dashboard/index.rst
> +Here you need to return an integer to set the weight of the service. Statistics with a higher priority will be displayed first.
Yes and I think we can add:
This is why we choose to use a negative value (**-1** for the first element, **-2** for the second...).

2020-01-28 09:39 UTC, loic425 commented on docs/cookbook/dashboard/index.rst
> +.. note::
maybe a warning instead? What do you think?

2020-01-28 09:40 UTC, loic425 requested changes

2020-01-28 09:40 UTC, loic425 commented on docs/cookbook/dashboard/index.rst
> +Add a new class to ``/src/Dashboad/Statistic`` and make sure it implement the ``App\Dashboard\Statistics\StatisticInterface``.
``/src/Dashboard/Statistic``
There's a typo on "Dashboard"

2020-02-06 18:13 UTC, loic425 approved these changes

2020-02-06 18:14 UTC, merged

2020-02-06 18:15 UTC, loic425 commented
Thanks @lucasballyn :1st_place_medal: